#!/usr/bin/env bash
read -p "Enter the first number: "  firstInput
read -p "Enter a second number: " secondInput

echo "The product of $firstInput and $secondInput is $((firstInput * secondInput))"
file="text.txt"

while read -r line; do
	touch "$line"
done <$file
